// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: alert-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Alert, AlertFilter, AlertID, AlertList } from "./alert";
import { Empty } from "./google/protobuf/Empty";

export const protobufPackage = "alert";

export type AlertServiceService = typeof AlertServiceService;
export const AlertServiceService = {
  upsertAlert: {
    path: "/alert.AlertService/UpsertAlert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Alert) => Buffer.from(Alert.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Alert.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  deleteAlert: {
    path: "/alert.AlertService/DeleteAlert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AlertID) => Buffer.from(AlertID.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AlertID.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  getAlert: {
    path: "/alert.AlertService/GetAlert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AlertID) => Buffer.from(AlertID.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AlertID.decode(value),
    responseSerialize: (value: Alert) => Buffer.from(Alert.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Alert.decode(value),
  },
  list: {
    path: "/alert.AlertService/List",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AlertFilter) => Buffer.from(AlertFilter.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AlertFilter.decode(value),
    responseSerialize: (value: AlertList) => Buffer.from(AlertList.encode(value).finish()),
    responseDeserialize: (value: Buffer) => AlertList.decode(value),
  },
} as const;

export interface AlertServiceServer extends UntypedServiceImplementation {
  upsertAlert: handleUnaryCall<Alert, Empty>;
  deleteAlert: handleUnaryCall<AlertID, Empty>;
  getAlert: handleUnaryCall<AlertID, Alert>;
  list: handleUnaryCall<AlertFilter, AlertList>;
}

export interface AlertServiceClient extends Client {
  upsertAlert(request: Alert, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  upsertAlert(
    request: Alert,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  upsertAlert(
    request: Alert,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteAlert(request: AlertID, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  deleteAlert(
    request: AlertID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteAlert(
    request: AlertID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  getAlert(request: AlertID, callback: (error: ServiceError | null, response: Alert) => void): ClientUnaryCall;
  getAlert(
    request: AlertID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Alert) => void,
  ): ClientUnaryCall;
  getAlert(
    request: AlertID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Alert) => void,
  ): ClientUnaryCall;
  list(request: AlertFilter, callback: (error: ServiceError | null, response: AlertList) => void): ClientUnaryCall;
  list(
    request: AlertFilter,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AlertList) => void,
  ): ClientUnaryCall;
  list(
    request: AlertFilter,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AlertList) => void,
  ): ClientUnaryCall;
}

export const AlertServiceClient = makeGenericClientConstructor(
  AlertServiceService,
  "alert.AlertService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AlertServiceClient;
  service: typeof AlertServiceService;
  serviceName: string;
};
