// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: alert.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Audit } from "./sologenic/com-fs-utils-lib/models/audit/audit";
import {
  MetaData,
  Network,
  networkFromJSON,
  networkToJSON,
} from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "alert";

export enum AlertStatus {
  DO_NOT_USE = 0,
  ACTIVE = 1,
  TRIGGERED = 2,
  CANCELLED = 3,
  UNRECOGNIZED = -1,
}

export function alertStatusFromJSON(object: any): AlertStatus {
  switch (object) {
    case 0:
    case "DO_NOT_USE":
      return AlertStatus.DO_NOT_USE;
    case 1:
    case "ACTIVE":
      return AlertStatus.ACTIVE;
    case 2:
    case "TRIGGERED":
      return AlertStatus.TRIGGERED;
    case 3:
    case "CANCELLED":
      return AlertStatus.CANCELLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AlertStatus.UNRECOGNIZED;
  }
}

export function alertStatusToJSON(object: AlertStatus): string {
  switch (object) {
    case AlertStatus.DO_NOT_USE:
      return "DO_NOT_USE";
    case AlertStatus.ACTIVE:
      return "ACTIVE";
    case AlertStatus.TRIGGERED:
      return "TRIGGERED";
    case AlertStatus.CANCELLED:
      return "CANCELLED";
    case AlertStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Alert {
  Alert: AlertDetails | undefined;
  MetaData: MetaData | undefined;
  Audit: Audit | undefined;
}

export interface AlertDetails {
  AlertID: number;
  Account: string;
  AssetKey: string;
  TargetPrice: number;
  Status: AlertStatus;
  OrganizationID: string;
}

export interface AssetKey {
  Account: string;
  AssetKey: string;
  OrganizationID: string;
  Network?: Network | undefined;
}

export interface AlertFilter {
  OrganizationID: string;
  Network?: Network | undefined;
  Offset?: number | undefined;
  Limit?: number | undefined;
}

export interface AlertList {
  Alerts: Alert[];
  TotalCount: number;
}

function createBaseAlert(): Alert {
  return { Alert: undefined, MetaData: undefined, Audit: undefined };
}

export const Alert = {
  encode(message: Alert, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Alert !== undefined) {
      AlertDetails.encode(message.Alert, writer.uint32(10).fork()).ldelim();
    }
    if (message.MetaData !== undefined) {
      MetaData.encode(message.MetaData, writer.uint32(18).fork()).ldelim();
    }
    if (message.Audit !== undefined) {
      Audit.encode(message.Audit, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Alert {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAlert();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Alert = AlertDetails.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.MetaData = MetaData.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Audit = Audit.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Alert {
    return {
      Alert: isSet(object.Alert) ? AlertDetails.fromJSON(object.Alert) : undefined,
      MetaData: isSet(object.MetaData) ? MetaData.fromJSON(object.MetaData) : undefined,
      Audit: isSet(object.Audit) ? Audit.fromJSON(object.Audit) : undefined,
    };
  },

  toJSON(message: Alert): unknown {
    const obj: any = {};
    if (message.Alert !== undefined) {
      obj.Alert = AlertDetails.toJSON(message.Alert);
    }
    if (message.MetaData !== undefined) {
      obj.MetaData = MetaData.toJSON(message.MetaData);
    }
    if (message.Audit !== undefined) {
      obj.Audit = Audit.toJSON(message.Audit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Alert>, I>>(base?: I): Alert {
    return Alert.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Alert>, I>>(object: I): Alert {
    const message = createBaseAlert();
    message.Alert = (object.Alert !== undefined && object.Alert !== null)
      ? AlertDetails.fromPartial(object.Alert)
      : undefined;
    message.MetaData = (object.MetaData !== undefined && object.MetaData !== null)
      ? MetaData.fromPartial(object.MetaData)
      : undefined;
    message.Audit = (object.Audit !== undefined && object.Audit !== null) ? Audit.fromPartial(object.Audit) : undefined;
    return message;
  },
};

function createBaseAlertDetails(): AlertDetails {
  return { AlertID: 0, Account: "", AssetKey: "", TargetPrice: 0, Status: 0, OrganizationID: "" };
}

export const AlertDetails = {
  encode(message: AlertDetails, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AlertID !== 0) {
      writer.uint32(8).int64(message.AlertID);
    }
    if (message.Account !== "") {
      writer.uint32(18).string(message.Account);
    }
    if (message.AssetKey !== "") {
      writer.uint32(26).string(message.AssetKey);
    }
    if (message.TargetPrice !== 0) {
      writer.uint32(33).double(message.TargetPrice);
    }
    if (message.Status !== 0) {
      writer.uint32(40).int32(message.Status);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(50).string(message.OrganizationID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AlertDetails {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAlertDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.AlertID = longToNumber(reader.int64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Account = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.AssetKey = reader.string();
          continue;
        case 4:
          if (tag !== 33) {
            break;
          }

          message.TargetPrice = reader.double();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AlertDetails {
    return {
      AlertID: isSet(object.AlertID) ? globalThis.Number(object.AlertID) : 0,
      Account: isSet(object.Account) ? globalThis.String(object.Account) : "",
      AssetKey: isSet(object.AssetKey) ? globalThis.String(object.AssetKey) : "",
      TargetPrice: isSet(object.TargetPrice) ? globalThis.Number(object.TargetPrice) : 0,
      Status: isSet(object.Status) ? alertStatusFromJSON(object.Status) : 0,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
    };
  },

  toJSON(message: AlertDetails): unknown {
    const obj: any = {};
    if (message.AlertID !== 0) {
      obj.AlertID = Math.round(message.AlertID);
    }
    if (message.Account !== "") {
      obj.Account = message.Account;
    }
    if (message.AssetKey !== "") {
      obj.AssetKey = message.AssetKey;
    }
    if (message.TargetPrice !== 0) {
      obj.TargetPrice = message.TargetPrice;
    }
    if (message.Status !== 0) {
      obj.Status = alertStatusToJSON(message.Status);
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AlertDetails>, I>>(base?: I): AlertDetails {
    return AlertDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AlertDetails>, I>>(object: I): AlertDetails {
    const message = createBaseAlertDetails();
    message.AlertID = object.AlertID ?? 0;
    message.Account = object.Account ?? "";
    message.AssetKey = object.AssetKey ?? "";
    message.TargetPrice = object.TargetPrice ?? 0;
    message.Status = object.Status ?? 0;
    message.OrganizationID = object.OrganizationID ?? "";
    return message;
  },
};

function createBaseAssetKey(): AssetKey {
  return { Account: "", AssetKey: "", OrganizationID: "", Network: undefined };
}

export const AssetKey = {
  encode(message: AssetKey, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Account !== "") {
      writer.uint32(10).string(message.Account);
    }
    if (message.AssetKey !== "") {
      writer.uint32(18).string(message.AssetKey);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(26).string(message.OrganizationID);
    }
    if (message.Network !== undefined) {
      writer.uint32(32).int32(message.Network);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AssetKey {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Account = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.AssetKey = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetKey {
    return {
      Account: isSet(object.Account) ? globalThis.String(object.Account) : "",
      AssetKey: isSet(object.AssetKey) ? globalThis.String(object.AssetKey) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
    };
  },

  toJSON(message: AssetKey): unknown {
    const obj: any = {};
    if (message.Account !== "") {
      obj.Account = message.Account;
    }
    if (message.AssetKey !== "") {
      obj.AssetKey = message.AssetKey;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssetKey>, I>>(base?: I): AssetKey {
    return AssetKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetKey>, I>>(object: I): AssetKey {
    const message = createBaseAssetKey();
    message.Account = object.Account ?? "";
    message.AssetKey = object.AssetKey ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    message.Network = object.Network ?? undefined;
    return message;
  },
};

function createBaseAlertFilter(): AlertFilter {
  return { OrganizationID: "", Network: undefined, Offset: undefined, Limit: undefined };
}

export const AlertFilter = {
  encode(message: AlertFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.OrganizationID !== "") {
      writer.uint32(10).string(message.OrganizationID);
    }
    if (message.Network !== undefined) {
      writer.uint32(24).int32(message.Network);
    }
    if (message.Offset !== undefined) {
      writer.uint32(32).int32(message.Offset);
    }
    if (message.Limit !== undefined) {
      writer.uint32(40).int32(message.Limit);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AlertFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAlertFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Offset = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.Limit = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AlertFilter {
    return {
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
      Limit: isSet(object.Limit) ? globalThis.Number(object.Limit) : undefined,
    };
  },

  toJSON(message: AlertFilter): unknown {
    const obj: any = {};
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    if (message.Limit !== undefined) {
      obj.Limit = Math.round(message.Limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AlertFilter>, I>>(base?: I): AlertFilter {
    return AlertFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AlertFilter>, I>>(object: I): AlertFilter {
    const message = createBaseAlertFilter();
    message.OrganizationID = object.OrganizationID ?? "";
    message.Network = object.Network ?? undefined;
    message.Offset = object.Offset ?? undefined;
    message.Limit = object.Limit ?? undefined;
    return message;
  },
};

function createBaseAlertList(): AlertList {
  return { Alerts: [], TotalCount: 0 };
}

export const AlertList = {
  encode(message: AlertList, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.Alerts) {
      Alert.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.TotalCount !== 0) {
      writer.uint32(16).int32(message.TotalCount);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AlertList {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAlertList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Alerts.push(Alert.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.TotalCount = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AlertList {
    return {
      Alerts: globalThis.Array.isArray(object?.Alerts) ? object.Alerts.map((e: any) => Alert.fromJSON(e)) : [],
      TotalCount: isSet(object.TotalCount) ? globalThis.Number(object.TotalCount) : 0,
    };
  },

  toJSON(message: AlertList): unknown {
    const obj: any = {};
    if (message.Alerts?.length) {
      obj.Alerts = message.Alerts.map((e) => Alert.toJSON(e));
    }
    if (message.TotalCount !== 0) {
      obj.TotalCount = Math.round(message.TotalCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AlertList>, I>>(base?: I): AlertList {
    return AlertList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AlertList>, I>>(object: I): AlertList {
    const message = createBaseAlertList();
    message.Alerts = object.Alerts?.map((e) => Alert.fromPartial(e)) || [];
    message.TotalCount = object.TotalCount ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
