// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: alert-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Alert, AlertFilter, AlertList, AssetKey } from "./alert";
import { Empty } from "./google/protobuf/Empty";

export const protobufPackage = "alert";

export type AlertServiceService = typeof AlertServiceService;
export const AlertServiceService = {
  upsert: {
    path: "/alert.AlertService/Upsert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Alert) => Buffer.from(Alert.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Alert.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  delete: {
    path: "/alert.AlertService/Delete",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AssetKey) => Buffer.from(AssetKey.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AssetKey.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  get: {
    path: "/alert.AlertService/Get",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AssetKey) => Buffer.from(AssetKey.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AssetKey.decode(value),
    responseSerialize: (value: Alert) => Buffer.from(Alert.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Alert.decode(value),
  },
  list: {
    path: "/alert.AlertService/List",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AlertFilter) => Buffer.from(AlertFilter.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AlertFilter.decode(value),
    responseSerialize: (value: AlertList) => Buffer.from(AlertList.encode(value).finish()),
    responseDeserialize: (value: Buffer) => AlertList.decode(value),
  },
} as const;

export interface AlertServiceServer extends UntypedServiceImplementation {
  upsert: handleUnaryCall<Alert, Empty>;
  delete: handleUnaryCall<AssetKey, Empty>;
  get: handleUnaryCall<AssetKey, Alert>;
  list: handleUnaryCall<AlertFilter, AlertList>;
}

export interface AlertServiceClient extends Client {
  upsert(request: Alert, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  upsert(
    request: Alert,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  upsert(
    request: Alert,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  delete(request: AssetKey, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  delete(
    request: AssetKey,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  delete(
    request: AssetKey,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  get(request: AssetKey, callback: (error: ServiceError | null, response: Alert) => void): ClientUnaryCall;
  get(
    request: AssetKey,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Alert) => void,
  ): ClientUnaryCall;
  get(
    request: AssetKey,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Alert) => void,
  ): ClientUnaryCall;
  list(request: AlertFilter, callback: (error: ServiceError | null, response: AlertList) => void): ClientUnaryCall;
  list(
    request: AlertFilter,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AlertList) => void,
  ): ClientUnaryCall;
  list(
    request: AlertFilter,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AlertList) => void,
  ): ClientUnaryCall;
}

export const AlertServiceClient = makeGenericClientConstructor(
  AlertServiceService,
  "alert.AlertService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AlertServiceClient;
  service: typeof AlertServiceService;
  serviceName: string;
};
