syntax = "proto3";

package alert;

import "sologenic/com-fs-utils-lib/models/metadata/metadata.proto";
import "sologenic/com-fs-utils-lib/models/audit/audit.proto";

option go_package = "github.com/sologenic/com-fs-alert-model;alert";

message Alert{
    AlertDetails Alert = 1;
    metadata.MetaData MetaData = 2;
    audit.Audit Audit = 3;
}
                                    
message AlertDetails {
    int64 AlertID = 1;
    string Account = 2;
    string AssetKey = 3;            
    double TargetPrice = 4;
    AlertStatus Status = 5;
    string OrganizationID = 6;
}


message AssetKey {
    string Account = 1;
    string AssetKey = 2;
    string OrganizationID = 3; 
    optional metadata.Network Network = 4; 
}

message AlertFilter {
    string OrganizationID = 1;
    optional metadata.Network Network = 3;
    optional int32 Offset = 4;
    optional int32 Limit = 5;
}

enum AlertStatus {
    DO_NOT_USE = 0;
    ACTIVE = 1;
    TRIGGERED = 2;
    CANCELLED = 3;
}

